#!/usr/bin/env python3
"""Build dist/spoolctl.py: the whole package as one runnable text file.

The artifact embeds every module's source verbatim and serves the `spoolctl`
package through an in-memory import finder, so intra-package imports work
unchanged in any order and the output stays readable. Needs only a Python
3.10+ interpreter to run.

Usage: python scripts/build_single_file.py [output_path]
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PACKAGE = REPO / "spoolctl"

MODULES = ["__init__", "models", "schemas", "store", "worker", "cli"]

TEMPLATE = '''\
#!/usr/bin/env python3
# spoolctl {version} — single-file build. https://github.com/Ozhiaki/spoolctl
# Generated by scripts/build_single_file.py; do not edit. Apache-2.0.
# Runs anywhere with Python 3.10+: `python3 spoolctl.py --help`

import sys

if sys.version_info < (3, 10):
    sys.stderr.write("spoolctl requires Python 3.10+\\n")
    sys.exit(3)

import importlib.abc
import importlib.util

_SOURCES = {sources}


class _EmbeddedFinder(importlib.abc.MetaPathFinder, importlib.abc.Loader):
    def find_spec(self, fullname, path=None, target=None):
        if fullname == "spoolctl" or fullname.split(".", 1)[0] == "spoolctl":
            short = "__init__" if fullname == "spoolctl" else fullname.split(".", 1)[1]
            if short in _SOURCES:
                return importlib.util.spec_from_loader(
                    fullname, self, is_package=(fullname == "spoolctl")
                )
        return None

    def create_module(self, spec):
        return None

    def exec_module(self, module):
        short = "__init__" if module.__name__ == "spoolctl" else module.__name__.split(".", 1)[1]
        code = compile(_SOURCES[short], f"{{__file__}}#{{module.__name__}}", "exec")
        module.__file__ = __file__
        exec(code, module.__dict__)


sys.meta_path.insert(0, _EmbeddedFinder())

if __name__ == "__main__":
    from spoolctl.cli import main
    sys.exit(main())
'''


def build(out_path: Path) -> None:
    sources = {name: (PACKAGE / f"{name}.py").read_text(encoding="utf-8") for name in MODULES}

    version = "unknown"
    for line in sources["models"].splitlines():
        if line.startswith("TOOL_VERSION"):
            version = line.split('"')[1]
            break

    body = TEMPLATE.format(version=version, sources=repr(sources))
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(body, encoding="utf-8")
    out_path.chmod(0o755)
    print(f"wrote {out_path} ({out_path.stat().st_size} bytes)")


if __name__ == "__main__":
    target = Path(sys.argv[1]) if len(sys.argv) > 1 else REPO / "dist" / "spoolctl.py"
    build(target)
