#!/usr/bin/env python3
"""Generate reference documentation from the spoolctl contract.

Usage:
    python3 scripts/build_docs.py            # write all generated pages
    python3 scripts/build_docs.py --check    # exit 1 and diff if any page is stale
    python3 scripts/build_docs.py --page verbs
"""

import argparse
import difflib
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DOCS = REPO / "docs"

HEADER = (
    "<!-- Generated by scripts/build_docs.py. Do not edit by hand. -->\n"
    "<!-- Regenerate: python3 scripts/build_docs.py -->\n\n"
)

sys.path.insert(0, str(REPO))

from spoolctl.cli import build_parser, _SUBPARSERS  # noqa: E402
from spoolctl.contract import build_capabilities  # noqa: E402
from spoolctl import models  # noqa: E402


def _caps():
    build_parser()
    data, _ = build_capabilities(_SUBPARSERS)
    return data


def _fmt_default(val):
    if val is None:
        return "none"
    if isinstance(val, bool):
        return str(val).lower()
    return str(val)


def _fmt_type(t):
    if t is None:
        return "string"
    return str(t)


def _safety_info(verb_data):
    parts = []
    s = verb_data.get("safety")
    if not s:
        return parts
    if s.get("confirmation_flag"):
        parts.append(f"confirmation: `{s['confirmation_flag']}`")
    if s.get("requires"):
        parts.append(f"requires: {', '.join(f'`{r}`' for r in s['requires'])}")
    if s.get("force_flag"):
        parts.append(f"force: `{s['force_flag']}`")
    if s.get("force_required_for"):
        parts.append(f"force required for: {s['force_required_for']}")
    if s.get("dry_run_flag"):
        parts.append(f"dry run: `{s['dry_run_flag']}`")
    if s.get("refusal_code"):
        parts.append(f"refusal: `{s['refusal_code']}`")
    return parts


# -- verbs.md ---------------------------------------------------------------

def _build_verbs(caps):
    lines = [HEADER, "# Verb Reference\n\n"]

    for name in sorted(caps["verbs"]):
        v = caps["verbs"][name]
        lines.append(f"## `{name}`\n\n")
        lines.append(f"{v['summary']}\n\n")

        # Positionals
        positionals = v.get("positionals") or v.get("args") or []
        if positionals:
            lines.append("### Positionals\n\n")
            lines.append("| Name | Type | Required | Description |\n")
            lines.append("|---|---|---|---|\n")
            for p in positionals:
                req = "yes" if p.get("required", False) else "no"
                desc = p.get("description", "")
                ptype = p.get("type", "string")
                if p.get("choices"):
                    ptype = "enum: " + ", ".join(f"`{c}`" for c in p["choices"])
                lines.append(f"| `{p['name']}` | {ptype} | {req} | {desc} |\n")
            lines.append("\n")

        # Flags
        flags = v.get("flags") or []
        if flags:
            lines.append("### Flags\n\n")
            lines.append("| Flag | Type | Default | Description |\n")
            lines.append("|---|---|---|---|\n")
            for f in flags:
                fname = f["flag"]
                aliases = [a for a in (f.get("aliases") or []) if a != fname]
                if aliases:
                    alias_str = " / " + " / ".join(f"`{a}`" for a in aliases)
                else:
                    alias_str = ""
                ftype = _fmt_type(f.get("type"))
                if f.get("choices"):
                    ftype = "enum: " + ", ".join(f"`{c}`" for c in f["choices"])
                if f.get("repeatable"):
                    ftype += " (repeatable)"
                default = _fmt_default(f.get("default"))
                desc = ""
                if f.get("minimum") is not None:
                    desc += f"min: {f['minimum']} "
                if f.get("maximum") is not None:
                    desc += f"max: {f['maximum']} "
                if f.get("unbounded"):
                    desc += "unbounded "
                desc = desc.strip()
                lines.append(f"| `{fname}`{alias_str} | {ftype} | {default} | {desc} |\n")
            lines.append("\n")

        # Output modes
        modes = v.get("output_modes") or []
        if modes:
            lines.append(f"**Output modes:** {', '.join(f'`{m}`' for m in modes)}\n\n")

        # Exit codes
        ecodes = v.get("exit_codes") or []
        if ecodes:
            lines.append(f"**Exit codes:** {', '.join(str(e) for e in sorted(ecodes))}\n\n")

        # Mutually exclusive groups
        mutex = v.get("mutually_exclusive") or []
        if mutex:
            for group in mutex:
                lines.append(f"**Mutually exclusive:** {' / '.join(f'`{g}`' for g in group)}\n\n")

        # Safety gates
        safety = _safety_info(v)
        if safety:
            lines.append(f"**Safety:** {', '.join(safety)}\n\n")

        # Traits
        traits = []
        if v.get("mutates"):
            traits.append("mutates")
        if v.get("destructive"):
            d = v["destructive"]
            traits.append(f"destructive ({d})" if isinstance(d, str) else "destructive")
        if v.get("idempotent"):
            i = v["idempotent"]
            traits.append(f"idempotent ({i})" if isinstance(i, str) else "idempotent")
        if traits:
            lines.append(f"**Traits:** {', '.join(traits)}\n\n")

        # Data schema
        if v.get("data_schema"):
            lines.append(f"**JSON data schema:** {v['data_schema']}\n\n")

        # Example
        examples = v.get("examples") or []
        if examples:
            lines.append("### Example\n\n")
            for ex in examples:
                lines.append(f"```bash\n{' '.join(ex)}\n```\n\n")

    return "".join(lines)


# -- errors.md --------------------------------------------------------------

def _build_errors(caps):
    lines = [HEADER, "# Error and Exit Code Reference\n\n"]

    # Exit codes — numeric order
    lines.append("## Exit Codes\n\n")
    lines.append("| Code | Meaning | Retryable |\n")
    lines.append("|---|---|---|\n")
    for code_str in sorted(caps["exit_codes"], key=int):
        entry = caps["exit_codes"][code_str]
        retryable = entry.get("retryable")
        ret_str = "yes" if retryable is True else ("no" if retryable is False else "n/a")
        meaning = entry["meaning"]
        note = entry.get("note", "")
        if note:
            meaning += f" ({note})"
        lines.append(f"| {code_str} | {meaning} | {ret_str} |\n")
    lines.append("\n")

    # Error codes from code_registry
    error_codes = sorted(
        code for code, entry in caps["code_registry"].items()
        if "errors" in entry["appears_in"]
    )
    warning_codes = sorted(
        code for code, entry in caps["code_registry"].items()
        if "warnings" in entry["appears_in"]
    )

    lines.append("## Error Codes\n\n")
    lines.append("| Code | Exit Code | Summary | Retryable |\n")
    lines.append("|---|---|---|---|\n")
    for code in error_codes:
        entry = caps["code_registry"][code]
        retryable = entry.get("retryable")
        ret_str = "yes" if retryable is True else ("no" if retryable is False else "n/a")
        lines.append(
            f"| `{code}` | {entry.get('exit_code', 'n/a')} "
            f"| {entry['summary']} | {ret_str} |\n"
        )
    lines.append("\n")

    lines.append("## Warning Codes\n\n")
    lines.append("| Code | Summary |\n")
    lines.append("|---|---|\n")
    for code in warning_codes:
        entry = caps["code_registry"][code]
        lines.append(f"| `{code}` | {entry['summary']} |\n")
    lines.append("\n")

    # Failure reasons — canonical order from the tuple
    lines.append("## Failure Reasons\n\n")
    lines.append(
        "Failure reasons are recorded on attempts to indicate why an attempt "
        "ended. The canonical order is preserved from the contract.\n\n"
    )
    lines.append("| Reason | Recorded By |\n")
    lines.append("|---|---|\n")
    reason_recorded_by = {
        "process_exit": "worker execution",
        "timeout": "worker execution",
        "spawn_failed": "worker execution",
        "worker_crash": "reaping",
        "canceled": "cancel and force-retry",
        "unknown": "historical backfill (ambiguous pre-v6 failures)",
    }
    for reason in models.FAILURE_REASONS:
        recorded = reason_recorded_by.get(reason, "")
        lines.append(f"| `{reason}` | {recorded} |\n")
    lines.append("\n")

    # Safety block codes
    lines.append("## Safety-Gated Verbs\n\n")
    lines.append(
        "These verbs have destructive or interrupting actions that require "
        "explicit confirmation.\n\n"
    )
    lines.append("| Verb | Confirmation | Refusal Code |\n")
    lines.append("|---|---|---|\n")
    for vname in sorted(caps["verbs"]):
        v = caps["verbs"][vname]
        if v.get("safety"):
            s = v["safety"]
            confirm = s.get("confirmation_flag") or s.get("force_flag", "")
            refusal = s.get("refusal_code", "")
            lines.append(f"| `{vname}` | `{confirm}` | `{refusal}` |\n")
    lines.append("\n")

    # Idempotency codes
    lines.append("## Idempotency Codes\n\n")
    lines.append(
        "These codes relate to idempotency key handling on the `add` verb.\n\n"
    )
    idem_codes = ["IDEMPOTENCY_CONFLICT", "IDEMPOTENCY_METADATA_DIFFERS"]
    lines.append("| Code | Type | Summary |\n")
    lines.append("|---|---|---|\n")
    for code in idem_codes:
        if code in caps["code_registry"]:
            entry = caps["code_registry"][code]
            appears = ", ".join(entry["appears_in"])
            lines.append(f"| `{code}` | {appears} | {entry['summary']} |\n")
    lines.append("\n")

    return "".join(lines)


# -- reference/limits.md ---------------------------------------------------

def _build_limits(caps):
    lines = [HEADER, "# Limits, Environment Variables, and Global Flags\n\n"]

    # Limits
    lines.append("## Limits\n\n")
    lines.append("| Name | Type | Minimum | Maximum | Unbounded |\n")
    lines.append("|---|---|---|---|---|\n")
    for name in sorted(caps["limits"]):
        entry = caps["limits"][name]
        ltype = entry.get("type", "")
        minimum = entry.get("minimum", "")
        maximum = entry.get("maximum", "")
        unbounded = "yes" if entry.get("unbounded") else "no"
        if minimum == "":
            minimum = "n/a"
        if maximum == "":
            maximum = "n/a"
        lines.append(f"| `{name}` | {ltype} | {minimum} | {maximum} | {unbounded} |\n")
    lines.append("\n")

    # Environment variables
    lines.append("## Environment Variables\n\n")
    lines.append("| Variable | Type | Default | Description |\n")
    lines.append("|---|---|---|---|\n")
    for name in sorted(caps["env_vars"]):
        entry = caps["env_vars"][name]
        etype = entry.get("type", "string")
        default = _fmt_default(entry.get("default"))
        desc = entry.get("description", "")
        consumed = entry.get("consumed_by", [])
        if consumed:
            desc += f" (consumed by: {', '.join(f'`{v}`' for v in consumed)})"
        lines.append(f"| `{name}` | {etype} | {default} | {desc} |\n")
    lines.append("\n")

    # Global flags
    lines.append("## Global Flags\n\n")
    gf = caps.get("global_flags", {})
    flags_list = gf.get("flags", [])
    if flags_list:
        lines.append("| Flag | Type | Description |\n")
        lines.append("|---|---|---|\n")
        for f in flags_list:
            fname = f.get("flag", f.get("name", ""))
            ftype = f.get("type", "boolean")
            desc = f.get("description", "")
            mode = f.get("output_mode", "")
            if mode:
                desc += f" (output: {mode})"
            lines.append(f"| `{fname}` | {ftype} | {desc} |\n")
        lines.append("\n")

    if gf.get("db_scope"):
        lines.append(f"**Database scope:** {gf['db_scope']}\n\n")

    return "".join(lines)


# -- reference/states.md ---------------------------------------------------

def _build_states(caps):
    lines = [HEADER, "# States, Events, Scheduling, and Execution\n\n"]

    # Job states — contract order
    lines.append("## Job States\n\n")
    lines.append("| State | Description |\n")
    lines.append("|---|---|\n")
    state_descriptions = {
        "queued": "Job is waiting to be claimed by a worker.",
        "running": "Job is currently being executed by a worker.",
        "done": "Job completed successfully.",
        "failed": "Job failed and may be retried (within retry budget).",
        "dead": "Job exhausted all retries and will not be retried.",
        "canceled": "Job was explicitly canceled.",
    }
    for state in caps["job_states"]:
        desc = state_descriptions.get(state, "")
        lines.append(f"| `{state}` | {desc} |\n")
    lines.append("\n")

    # Attempt states — contract order
    lines.append("## Attempt States\n\n")
    lines.append("| State | Description |\n")
    lines.append("|---|---|\n")
    attempt_descriptions = {
        "running": "Attempt is currently executing.",
        "succeeded": "Attempt completed with exit code 0.",
        "failed": "Attempt completed with non-zero exit code.",
        "timed_out": "Attempt exceeded the per-job timeout.",
        "abandoned": "Attempt was abandoned due to worker crash.",
        "canceled": "Attempt was canceled.",
    }
    for state in caps["attempt_states"]:
        desc = attempt_descriptions.get(state, "")
        lines.append(f"| `{state}` | {desc} |\n")
    lines.append("\n")

    # Events — contract order from the tuple
    lines.append("## Event Types\n\n")
    lines.append("| Event | Description |\n")
    lines.append("|---|---|\n")
    event_descriptions = {
        "added": "A new job was added to the queue.",
        "claimed": "A worker claimed the job for execution.",
        "succeeded": "The attempt completed successfully.",
        "failed": "The attempt failed with a non-zero exit code.",
        "timed_out": "The attempt exceeded the per-job timeout.",
        "reaped": "A crashed worker's attempt was recovered.",
        "dead": "The job exhausted all retries.",
        "retried": "A failed or crashed job was re-queued for another attempt.",
        "canceled": "The job was explicitly canceled.",
    }
    for event in models.JOB_EVENT_TYPES:
        desc = event_descriptions.get(event, "")
        lines.append(f"| `{event}` | {desc} |\n")
    lines.append("\n")

    # Scheduling capabilities
    lines.append("## Scheduling\n\n")
    sched = caps.get("scheduling", {})
    if sched:
        _emit_nested_table(lines, sched)

    # Execution capabilities
    lines.append("## Execution\n\n")
    exe = caps.get("execution", {})
    if exe:
        _emit_nested_table(lines, exe)

    return "".join(lines)


def _emit_nested_table(lines, data, depth=0):
    """Emit a nested dict as a readable Markdown section."""
    for key in sorted(data):
        val = data[key]
        prefix = "  " * depth
        if isinstance(val, dict):
            lines.append(f"{prefix}**{key}:**\n\n")
            _emit_nested_table(lines, val, depth + 1)
        elif isinstance(val, (list, tuple)):
            items = ", ".join(f"`{v}`" if isinstance(v, str) else str(v) for v in val)
            lines.append(f"{prefix}**{key}:** {items}\n\n")
        else:
            lines.append(f"{prefix}**{key}:** `{val}`\n\n")


# -- dispatch ---------------------------------------------------------------

PAGES = {
    "verbs": ("docs/verbs.md", _build_verbs),
    "errors": ("docs/errors.md", _build_errors),
    "limits": ("docs/reference/limits.md", _build_limits),
    "states": ("docs/reference/states.md", _build_states),
}


def main():
    parser = argparse.ArgumentParser(description="Generate spoolctl reference docs.")
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 with diff if any page is stale.")
    parser.add_argument("--page", choices=list(PAGES),
                        help="Generate a single page.")
    args = parser.parse_args()

    caps = _caps()
    targets = {args.page: PAGES[args.page]} if args.page else PAGES

    stale = False
    for name, (rel_path, builder) in sorted(targets.items()):
        path = REPO / rel_path
        content = builder(caps)

        if args.check:
            if not path.exists():
                print(f"MISSING: {rel_path}", file=sys.stderr)
                print(f"Regenerate: python3 scripts/build_docs.py", file=sys.stderr)
                stale = True
                continue
            existing = path.read_text()
            if existing != content:
                diff = difflib.unified_diff(
                    existing.splitlines(keepends=True),
                    content.splitlines(keepends=True),
                    fromfile=f"a/{rel_path}",
                    tofile=f"b/{rel_path}",
                )
                sys.stdout.writelines(diff)
                print(f"\nStale: {rel_path}", file=sys.stderr)
                print(f"Regenerate: python3 scripts/build_docs.py", file=sys.stderr)
                stale = True
                continue
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            print(f"wrote {rel_path}")

    if stale:
        sys.exit(1)


if __name__ == "__main__":
    main()
